# This is a basic workflow to help you get started with Actions

name: ppc64le runner ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build
  ppc64le:
      runs-on: ppc64le
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install preflight 
        run: |
          wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-ppc64le
          chmod u+x preflight-linux-ppc64le
          sudo mv preflight-linux-ppc64le /usr/local/bin/preflight
          preflight --version
          
      - name: Check container image
        run: |
          preflight check container quay.io/mayurwaghmode111/demo-container-image:power
          
      - name: Login to image registry
        run: |
          docker login --username mayurwaghmode111 --password Mpersistentchess@123 quay.io
        
      - name: Submit the certification results to Red Hat
        run: |
          sudo preflight check container quay.io/mayurwaghmode111/demo-container-image:power --submit --pyxis-api-token=3h5l3mm9uefqdax2jyw5ph8hgmjqt7rx --certification-project-id=627ceb064f78694e73246f3e --docker-config=/home/runner/.docker/config.json

        
