name: Multiarch build

on:
  push:
      
jobs:
  certify:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Install preflight
      run: |
        echo ${{ secrets.ARCH }}
        wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-${{ secrets.ARCH }}
        chmod u+x preflight-linux-${{ secrets.ARCH }}
        sudo mv preflight-linux-${{ secrets.ARCH }}" /usr/local/bin/preflight
        preflight --version
        
    - name: Check container-image
      run: |
        preflight check container ${{ secrets.IMAGE_REGISTRY }}/${{ secrets.IMAGE_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
        
    - name: Login to image registry
      run: |
        docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} ${{ secrets.IMAGE_REGISTRY }}
      
    - name: Submit the certification results to Red Hat
      run: |
        sudo preflight check container  ${{ secrets.IMAGE_REGISTRY }}/${{ secrets.IMAGE_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} --submit --pyxis-api-token=${{ secrets.PYXIS_API_TOKEN }} --certification-project-id=${{ secrets.PROJECT_ID }} --docker-config=/root/.docker/config.json
