on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ppc64le
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: darsvador/run-on-arch-action@v1.0.10
        id: runcmd
        with:
          architecture: ppc64le
          distribution: ubuntu18.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-ppc64le
            chmod u+x preflight-linux-ppc64le
            sudo mv preflight-linux-ppc64le /usr/local/bin/preflight
            preflight --version
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
