on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ppc64le
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: darsvador/run-on-arch-action@v1.0.10
        id: runcmd
        with:
          architecture: ppc64le
          distribution: ubuntu18.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
