on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-20.04
    name: Build on ppc64le
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        id: runcmd
        with:
          architecture: ppc64le
          distribution: ubuntu20.04
          run: |
            uname -a
            apt install curl
            curl -OL https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-ppc64le
            chmod u+x preflight-linux-ppc64le
            mv preflight-linux-ppc64le /usr/local/bin/preflight
            preflight --version
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
