on: [push, pull_request]

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  ARCH: ${{ secrets.ARCH }}
  PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-22.04 ppc64le
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ppc64le
          distro: ubuntu_latest

          run: |
            uname -a
            sudo apt-get install wget
            wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-ppc64le
            chmod u+x preflight-linux-ppc64le
            sudo mv preflight-linux-ppc64le /usr/local/bin/preflight
            preflight --version

     
