name: Multiarch build

on:
  push:
 
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  ARCH: ${{ secrets.ARCH }}
  PYXIS_API_TOKEN: ${{ secrets.PYXIS_API_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
   
   
jobs:
  certify:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Install preflight 
      run: |
        wget https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.2.0/preflight-linux-ppc64le
        chmod u+x preflight-linux-ppc64le
        sudo mv preflight-linux-ppc64le /usr/local/bin/preflight
        preflight --version
        
    - name: Check container-image
      run: |
        preflight check container "$IMAGE_REGISTRY"/"$IMAGE_NAMESPACE"/"$IMAGE_NAME":"$IMAGE_TAG"
        
    - name: Login to image registry
      run: |
        docker login --username "$USERNAME" --password "$PASSWORD" "$IMAGE_REGISTRY"
      
    - name: Submit the certification results to Red Hat
      run: |
        sudo preflight check container "$IMAGE_REGISTRY"/"$IMAGE_NAMESPACE"/"$IMAGE_NAME":"$IMAGE_TAG" --submit --pyxis-api-token="$PYXIS_API_TOKEN" --certification-project-id="$PROJECT_ID" --docker-config=/home/runner/.docker/config.json
